export default {
  allowedCommandList: [
    'essence',
    'player',
    'slayer',
    'ms',
    'nw',
    'targetpractice',
    'ginfo',
    'wealth',
    'sbprofiles',
    'cata',
    'sbskills',
    'player',
    'inventory',
    'weight',
    'sbpets',
    'sbhotm',
    'crimson',
    'trophyfish',
    'check-dungeon',
    'check-kuudra',
    'pcheck-dungeon',
    'pcheck-kuudra',
  ],
  allowedPostCommandList: ['pcheck-dungeon', 'pcheck-kuudra'],
};
